#!/bin/sh
### BEGIN INIT INFO
# Provides:          umountfs
# Required-Start:
# Required-Stop:     
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Turn off swap and unmount all local file systems.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo "Deactivating swap..."
swapoff -a

# Unmount everything but tmpfs 
echo "Unmounting local filesystems..."
grep -v tmpfs /etc/mtab | sed 'x;1!H;$!d;x' | awk '{umount $2}'

: exit 0
